# Convert and pre-process data

This notebook converts the .xlsx file to .csv, which will be used later for data pre-processing and at the end a new dataframe will be generated that can be used for possible analysis.

In [3]:
import pandas as pd

##XLSX
df = pd.read_excel('files_csv/neuro_deep_evaluation.xlsx')

##CSV
df.to_csv('df_neuron.csv', index=False, encoding='utf-8')

## Data cleaning

* Convert string to lowercase
* Remove accents
* Remove spaces after commas

Code used https://www.kaggle.com/code/limajr/analyzing-stories-of-brazilian-telecom-customers/notebook

In [4]:
df.head()

,work,Year,Publication type,Cell-classes,Cell-types,How many classes/types of neurons?,What type of classification problems?,Region,Subregion,Species,What is the data source?,What data representation is being used?,What features are extracted?,What classification methods are being used?,Types of ANN,What neuroscience tools and technologies are being used?,Is the source code available?,What programming language are being used?,What evaluation measures are being used?,Other relevant aspects
0,"Batabyal, T., Condron, B., & Acton, S. T. (202...",2020,Journal,"pyramidal, ganglion, granule, motoneuron, purk...",only classes,5 classes,multi-class,"neocortex, hippocampus","neocortex_occipital, neocortex_prefrontal, neo...",mouse,Neuromorpho,Graph-based,morphometrics_features,"KNN, SVM",Does_not_use_ANN,"NeuroSol, TMD, NeuroPath2Path",Yes. Github,matlab,"Accuracy, Confusion_Matrix",Path2path is being compared against TMD - prop...
1,"Grbatinić, I., Milošević, N., & Krstonošić, B....",2018,Journal,interneuron,caudate (CIN) and putaminal neuron type (PIN),"1 class, 2 types",binary,neostriate_nuclei,neostriate_nuclei,human,Own_dataset,"image-based, Skeleton-Based",morphometrics_features,"Neural_Networks, K-means, Linear Discriminant...","Multi Layer Perceptron, Kohonen map",Not_used,No,not_described,"AUC, sensitivity",NaN
2,"Kanari, L., Ramaswamy, S., Shi, Y., Morand, S....",2019,Journal,pyramidal,not_described,"1 class, 17 types",multi-class,Somatosensory,cortex_somatosensory,rat,Own_dataset,Skeleton-Based,"Topological_features, morphometrics_features",not_described,Does_not_use_ANN,TMD,No,not_described,"Accuracy, Confusion_Matrix",They do a reclassification. The misclassified ...
3,"Kirch, C., & Gollo, L. L. (2020). Spatially re...",2020,Journal,"pyramidal, purkinje, ganglion, sensory, granul...",only classes,6 classes,multi-class,"neocortex, hippocampus, cerebellum, forebarin,...","cortex_occipital, cortex_frontal, cortex_tempo...","mouse, human, rat, wallaby, Drosophila_melanog...",Neuromorpho,point-based,Topological_features,not_described,Does_not_use_ANN,Not_used,Yes. Systems Neuroscience Group erro link,Matlab,not_described,This paper provides insights into the role the...
4,"Laturnus, S., Kobak, D., & Berens, P. (2020). ...",2020,Journal,interneuron,not_described,"1 class, 11 types",multi-class,"retina, neocortex","retina, cortex",mouse,Third party,point-based,"Density_maps, morphometrics_features, Topologi...","Logistic_regression, KNN, Decision_Tree",Does_not_use_ANN,NLMorphologyConverter,Yes. Github,Python,"Cross-validation, Accuracy, F1-Score",This work evaluates representations of morphol...

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('df_neuron.csv')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 20 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   work                                                      35 non-null     object
 1   Year                                                      35 non-null     int64
 2   Publication type                                          35 non-null     object
 3   Cell-classes                                              35 non-null     object
 4   Cell-types                                                35 non-null     object
 5   How many classes/types of neurons?                        35 non-null     object
 6   What type of classification problems?                     35 non-null     object
 7   Region                                                    35 non-null     object
 8   Subregion                                                 35 non-null     object
 9   Species                                                   35 non-null     object
 10  What is the data source?                                  35 non-null     object
 11  What data representation is being used?                   35 non-null     object
 12  What features are extracted?                              35 non-null     object
 13  What classification methods are being used?               35 non-null     object
 14  Types of ANN                                              35 non-null     object
 15  What neuroscience tools and technologies are being used?  35 non-null     object
 16  Is the source code available?                             35 non-null     object
 17  What programming language are being used?                 35 non-null     object
 18  What evaluation measures are being used?                  35 non-null     object
 19  Other relevant aspects                                    8 non-null      object
dtypes: int64(1), object(19)
memory usage: 5.6+ KB

### Rename columns

In [8]:
##Removing whitespace in each column name
df = df.rename(columns=lambda x: x.replace(" ", "_"))

In [9]:
df.head()

,work,Year,Publication_type,Cell-classes,Cell-types,How_many_classes/types_of_neurons?,What_type_of_classification_problems?,Region,Subregion,Species,What_is_the_data_source?,What_data_representation_is_being_used?,What_features_are_extracted?,What_classification_methods_are_being_used?,Types_of_ANN,What_neuroscience_tools_and_technologies_are_being_used?,Is_the_source_code_available?,What_programming_language_are_being_used?,What_evaluation_measures_are_being_used?,Other_relevant_aspects
0,"Batabyal, T., Condron, B., & Acton, S. T. (202...",2020,Journal,"pyramidal, ganglion, granule, motoneuron, purk...",only classes,5 classes,multi-class,"neocortex, hippocampus","neocortex_occipital, neocortex_prefrontal, neo...",mouse,Neuromorpho,Graph-based,morphometrics_features,"KNN, SVM",Does_not_use_ANN,"NeuroSol, TMD, NeuroPath2Path",Yes. Github,matlab,"Accuracy, Confusion_Matrix",Path2path is being compared against TMD - prop...
1,"Grbatinić, I., Milošević, N., & Krstonošić, B....",2018,Journal,interneuron,caudate (CIN) and putaminal neuron type (PIN),"1 class, 2 types",binary,neostriate_nuclei,neostriate_nuclei,human,Own_dataset,"image-based, Skeleton-Based",morphometrics_features,"Neural_Networks, K-means, Linear Discriminant...","Multi Layer Perceptron, Kohonen map",Not_used,No,not_described,"AUC, sensitivity",NaN
2,"Kanari, L., Ramaswamy, S., Shi, Y., Morand, S....",2019,Journal,pyramidal,not_described,"1 class, 17 types",multi-class,Somatosensory,cortex_somatosensory,rat,Own_dataset,Skeleton-Based,"Topological_features, morphometrics_features",not_described,Does_not_use_ANN,TMD,No,not_described,"Accuracy, Confusion_Matrix",They do a reclassification. The misclassified ...
3,"Kirch, C., & Gollo, L. L. (2020). Spatially re...",2020,Journal,"pyramidal, purkinje, ganglion, sensory, granul...",only classes,6 classes,multi-class,"neocortex, hippocampus, cerebellum, forebarin,...","cortex_occipital, cortex_frontal, cortex_tempo...","mouse, human, rat, wallaby, Drosophila_melanog...",Neuromorpho,point-based,Topological_features,not_described,Does_not_use_ANN,Not_used,Yes. Systems Neuroscience Group erro link,Matlab,not_described,This paper provides insights into the role the...
4,"Laturnus, S., Kobak, D., & Berens, P. (2020). ...",2020,Journal,interneuron,not_described,"1 class, 11 types",multi-class,"retina, neocortex","retina, cortex",mouse,Third party,point-based,"Density_maps, morphometrics_features, Topologi...","Logistic_regression, KNN, Decision_Tree",Does_not_use_ANN,NLMorphologyConverter,Yes. Github,Python,"Cross-validation, Accuracy, F1-Score",This work evaluates representations of morphol...

### Converting string to lowercase and removing accents

In [10]:
import unicodedata
from unicodedata import normalize
import re

In [11]:
##Defining function that converts to lowercase and removes accents
def pre_processing(text):
    ##text adaptation 
    adp_text = str(text).lower()
    acent_text = normalize('NFKD', adp_text).encode('ASCII','ignore').decode('ASCII')
    return acent_text

In [12]:
##Apply function all Dataframe
df = df.applymap(pre_processing)

In [13]:
##Remove spaces after commas
df = df.replace(', ', ',', regex=True)
df = df.replace(' ,', ',', regex=True)
df = df.replace(' ','_', regex=True)

In [14]:
df.head(3)

,work,Year,Publication_type,Cell-classes,Cell-types,How_many_classes/types_of_neurons?,What_type_of_classification_problems?,Region,Subregion,Species,What_is_the_data_source?,What_data_representation_is_being_used?,What_features_are_extracted?,What_classification_methods_are_being_used?,Types_of_ANN,What_neuroscience_tools_and_technologies_are_being_used?,Is_the_source_code_available?,What_programming_language_are_being_used?,What_evaluation_measures_are_being_used?,Other_relevant_aspects
0,"batabyal,t.,condron,b.,&_acton,s._t._(2020)._n...",2020,journal,"pyramidal,ganglion,granule,motoneuron,purkinje",only_classes,5_classes,multi-class,"neocortex,hippocampus","neocortex_occipital,neocortex_prefrontal,neoco...",mouse,neuromorpho,graph-based_,morphometrics_features,"knn,svm",does_not_use_ann,"neurosol,tmd,neuropath2path",yes._github_,matlab,"accuracy,confusion_matrix",path2path_is_being_compared_against_tmd_-_prop...
1,"grbatinic,i.,milosevic,n.,&_krstonosic,b._(201...",2018,journal,interneuron,caudate_(cin)_and_putaminal_neuron_type_(pin),"1_class,2_types",binary,neostriate_nuclei,neostriate_nuclei,human,own_dataset,"image-based,skeleton-based",morphometrics_features,"neural_networks,k-means,_linear_discriminant_a...","multi_layer_perceptron,kohonen_map",not_used,no,not_described,"auc,sensitivity",nan
2,"kanari,l.,ramaswamy,s.,shi,y.,morand,s.,meystr...",2019,journal,pyramidal,not_described,"1_class,17_types",multi-class,somatosensory,cortex_somatosensory,rat,own_dataset,skeleton-based,"topological_features,morphometrics_features_",not_described,does_not_use_ann,tmd,no,not_described,"accuracy,confusion_matrix",they_do_a_reclassification._the_misclassified_...

In [15]:
df.to_csv('files_csv/prep_neuron.csv')